/* Single-bundle builder for fe/liveops (2026-10-05).
   The shared tree currently has other coordinators' unregistered game files
   in flight (master-calendar.js, cell-comp-seasons.js, cell-territory-map.js),
   so the full build/bundle.js validator fails on THEIR files — not this
   branch's concern. This script builds ONLY bundle-warroom.js with the exact
   same transform as build/bundle.js --debug (header, concat, semicolon
   guard, node --check + new Function validation, inner-script syntax gate).
   Usage: node scripts/build-warroom.mjs */
import { execFileSync, execSync } from 'node:child_process';
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

var HERE = dirname(fileURLToPath(import.meta.url));
var ROOT = join(HERE, '..', 'v1.4.3', 'games');
var NAME = 'bundle-warroom';
var FILES = ['liveops.js'];

/* Inner-script syntax gate (same as build/bundle.js). */
execFileSync(process.execPath, [join(HERE, 'check-inner-scripts.js'), join(ROOT, 'liveops.js')],
  { stdio: 'inherit' });

var out = [];
out.push('/* PF v1.4.3 ' + NAME + '.js — concatenated bundle, generated by build/bundle.js.');
out.push('   DO NOT EDIT. Regenerate with: node build/bundle.js [--debug]');
out.push('   Contains: ' + FILES.join(', '));
out.push('   Each silo keeps its own PF.skip() kill switch (?pf_off=<silo>). */');
FILES.forEach(function (f) {
  out.push('\n/* ===== ' + f + ' ===== */');
  out.push(readFileSync(join(ROOT, f), 'utf8'));
  out.push(';');
});
var raw = out.join('\n');
var dest = join(ROOT, NAME + '.js');
writeFileSync(dest, raw);
execSync('node --check ' + dest, { stdio: 'pipe' });
new Function(readFileSync(dest, 'utf8'));
console.log(NAME + '.js: ' + (statSync(dest).size / 1024).toFixed(1) + ' KB — OK');
